### ISSUE TITLE
Login Page 

### ISSUE THREAD

**Issue by suntwalriya** [sanscript-tech/medical-emergency-flutter-node#14]
- Add the code for the login page
![3-Login](https://user-images.githubusercontent.com/41776149/97114033-2441aa00-1714-11eb-81db-03fcfde59fe6.PNG)

**Comment by Masters-Akt** [comment]
Do we have to code the login page or first submit the wireframe here?

**Comment by suntwalriya** [comment]
This issue is for the code, wireframes are to submitted on other issue.

**Comment by Manthan109** [comment]
I had to like to work on this

**Comment by manthanguptaa** [comment]
I had like to work on the login and register page

**Comment by Masters-Akt** [comment]
I was waiting for the wireframing to start working on this issue.

**Comment by suntwalriya** [comment]
@Masters-Akt I see you were not assigned this in the first week, where you could have started by commenting on this issue that you wanted to work in future. It is okay, there are a lot more issues to start with and i am here to help you with all of them.
