### ISSUE TITLE
SignUp Page

### ISSUE THREAD

**Issue by suntwalriya** [sanscript-tech/medical-emergency-flutter-node#15]
- Add the SignUp Page code
![image](https://user-images.githubusercontent.com/41776149/97116251-f9f6e900-1721-11eb-8aaf-30f224409226.png)

**Comment by Geeky-star** [comment]
I would like to build signup page.

**Comment by suntwalriya** [comment]
Please text us on Slack channel, thank you !

**Comment by Masters-Akt** [comment]
i would like to work on this.

**Comment by manthanguptaa** [comment]
Assign me this too

**Comment by suntwalriya** [comment]
@Masters-Akt any updates?

**Comment by Masters-Akt** [comment]
working on it

**Comment by suntwalriya** [comment]
@Manthan109 if you want to work on this, go ahead, assign yourself!
