### ISSUE TITLE
Dashboard Page

### ISSUE THREAD

**Issue by suntwalriya** [sanscript-tech/medical-emergency-flutter-node#16]
- Add the Dashboard Page Code including the OAuth icons

![image](https://user-images.githubusercontent.com/41776149/97116224-d2a01c00-1721-11eb-957f-f9d9a1158933.png)

**Comment by manthanguptaa** [comment]
I had like to work on this

**Comment by suntwalriya** [comment]
The App's name is HelloDoc and the logo will be provided to you by tomorrow.
