### ISSUE TITLE
Create a user model

### ISSUE THREAD

**Issue by BhavyaaArora-08** [sanscript-tech/medical-emergency-flutter-node#19]
A user must have the following fields.
1. Name
2. Phone No
3. Email
4. Address
5. Password
6. Tokens 

An access token ( json-web-token ) will be given to the user when he or she registers/logs in
This token will be used for authorization of the user, for accessing private routes.

**Comment by Arnab-31** [comment]
Are we going to implement this in mongoDB?

**Comment by BhavyaaArora-08** [comment]
Yes

**Comment by harshareddy794** [comment]
Can I work on the issue? @Codess08

**Comment by BhavyaaArora-08** [comment]
Yes, @harshareddy794  
Thanks for contributing.

**Comment by BhavyaaArora-08** [comment]
@harshareddy794  Are you working on the issue?

**Comment by harshareddy794** [comment]
Yes I'm working on it @Codess08 
Will make a PR by tomorrow

**Comment by harshareddy794** [comment]
PR for this issue has been merged please close this issue @carrisunrio  @Codess08
