### ISSUE TITLE
Create a route for registering a user.

### ISSUE THREAD

**Issue by BhavyaaArora-08** [sanscript-tech/medical-emergency-flutter-node#20]
It should look like this :- 

@route  POST api/users 
@desc  Register user
@access Public

This must be a public route, implies no verification is required to access this route.

**Comment by harshareddy794** [comment]
Can I work on this issue?

**Comment by BhavyaaArora-08** [comment]
Yes, @harshareddy794

**Comment by BhavyaaArora-08** [comment]
Are you working on the issue? @harshareddy794

**Comment by harshareddy794** [comment]
Yes will make a PR by tomorrow @Codess08

**Comment by BhavyaaArora-08** [comment]
Is the PR ready?

**Comment by harshareddy794** [comment]
I'll make it today

**Comment by BhavyaaArora-08** [comment]
We can't give more than 7 days to submit a PR. 
Please make the PR asap.

**Comment by harshareddy794** [comment]
@Codess08  Will make a PR today

**Comment by BhavyaaArora-08** [comment]
@harshareddy794, I will have to unassign you this issue.
It is a strict rule to not give more than 7 days on a PR.
