### ISSUE TITLE
Create a route for logging a user

### ISSUE THREAD

**Issue by BhavyaaArora-08** [sanscript-tech/medical-emergency-flutter-node#21]
@route  POST api/users/login
@desc  Login user
@access Public

**Comment by Arnab-31** [comment]
Can I work on this issue?

**Comment by BhavyaaArora-08** [comment]
Yes @Arnab-31 
Thanks for contributing.

**Comment by BhavyaaArora-08** [comment]
Are you working on the issue? @Arnab-31

**Comment by Arnab-31** [comment]
Yes, I will send a PR soon.

**Comment by Arnab-31** [comment]
Once a user logs in ,should I send a cookie with the jwt token stored in it like we do in web apps or is it needed to be done in a different way?

**Comment by BhavyaaArora-08** [comment]
Check the response format I have sent in the group.
Simply return the token.

If there is anything you want to ask about jsonwebtoken, let me know I can send you resources you can refer to.
