### ISSUE TITLE
Create a route for accessing the details of the logged in user.

### ISSUE THREAD

**Issue by BhavyaaArora-08** [sanscript-tech/medical-emergency-flutter-node#23]
@route   GET api/users
@desc    Get yourself
@access  Private

**Comment by KN999** [comment]
Can I work on this?

**Comment by BhavyaaArora-08** [comment]
Yes @KN999 
Thanks for contributing

**Comment by BhavyaaArora-08** [comment]
Are you working on the issue? @KN999

**Comment by KN999** [comment]
Yes, @Codess08  I am working on it.

**Comment by BhavyaaArora-08** [comment]
Okay, do have a look at the response format I have sent in the slack channel.

**Comment by KN999** [comment]
Sure
