### ISSUE TITLE
Hospital Details Page

### ISSUE THREAD

**Issue by suntwalriya** [sanscript-tech/medical-emergency-flutter-node#37]
![12-Hospital Detail page](https://user-images.githubusercontent.com/41776149/97114188-09bc0080-1715-11eb-9750-3918e5be1c05.PNG)

**Comment by Shubham-1105** [comment]
I want to work on this

**Comment by samflab** [comment]
assigned you this issue!

**Comment by suntwalriya** [comment]
Please rename files so that they are easily recognisable. Make PR in each of the issues separately, thank you!
