### ISSUE TITLE
Drawer

### ISSUE THREAD

**Issue by suntwalriya** [sanscript-tech/medical-emergency-flutter-node#4]
- A vertical drawer for the overview of the app

![10-Drawer](https://user-images.githubusercontent.com/41776149/97114162-d6797180-1714-11eb-910d-2a9d4b7b7bcf.PNG)

**Comment by Geeky-star** [comment]
Please, assign this issue to me.

**Comment by Shubham-1105** [comment]
I want to work on this

**Comment by samflab** [comment]
assigned you!

**Comment by samflab** [comment]
@Shubham-1105 updates on this?
