### ISSUE TITLE
Ambulance Page

### ISSUE THREAD

**Issue by suntwalriya** [sanscript-tech/medical-emergency-flutter-node#40]
![image](https://user-images.githubusercontent.com/41776149/97116141-2a8a5300-1721-11eb-9c62-c7eaeff001d2.png)

**Comment by Shubham-1105** [comment]
I want to work on this

**Comment by carrisunrio** [comment]
You can only comment on 2 issues at a time.

**Comment by manthanguptaa** [comment]
I want to work on this issue
