### ISSUE TITLE
Create server.js, mongoose.js

### ISSUE THREAD

**Issue by BhavyaaArora-08** [sanscript-tech/medical-emergency-flutter-node#43]
- [ ] server.js file will serve as the entry point.

- [ ] In mongoose.js you have to connect to mongodb database.

Please have a look at the file structure in the main repository,

**Comment by harshareddy794** [comment]
Can I work on the issue @Codess08?

**Comment by BhavyaaArora-08** [comment]
Yes @harshareddy794
