### ISSUE TITLE
Create profile model.

### ISSUE THREAD

**Issue by BhavyaaArora-08** [sanscript-tech/medical-emergency-flutter-node#44]
- [ ] A profile should have a user field that refers to a user.
- [ ] Other fields include doctors consulted, hospitals visited etc. 

Refer user profile page from the UI sent in the group.

**Comment by Shubham-1105** [comment]
I want to work on this

**Comment by BhavyaaArora-08** [comment]
Thanks for contributing.

**Comment by BhavyaaArora-08** [comment]
@Shubham-1105 are you working on this?

**Comment by Shubham-1105** [comment]
Yes
