### ISSUE TITLE
Get all user profiles

### ISSUE THREAD

**Issue by BhavyaaArora-08** [sanscript-tech/medical-emergency-flutter-node#46]
@route GET api/profile 
@desc Get all user profiles 
@access Public

**Comment by Arnab-31** [comment]
Can I work on this issue?

**Comment by BhavyaaArora-08** [comment]
Thanks for contributing.

**Comment by Arnab-31** [comment]
@Codess08 kindly merge the PR which adds the server file to the project. Without that, it's not possible to test any back end feature.

**Comment by BhavyaaArora-08** [comment]
Actually that PR is not up to date with the file structure.
Let's do one thing since everyone is familiar with the file structure I discussed in the meeting and shared in the slack as well, it is better to stick to it only.

I will create a new issue "Update File Structure"
You take that issue up it will fetch you 10 points and I will merge @harshareddy794 's PR asap.

**Comment by Arnab-31** [comment]
Yeah that sounds good.

**Comment by BhavyaaArora-08** [comment]
Is the PR ready?

**Comment by Arnab-31** [comment]
I will make it by today

**Comment by Arnab-31** [comment]
@Codess08 what are the fields of a user this route should return?
Currently, I am returning the id, name, email, phoneNo, Address, date, createdAt, updatedAt.
Would you like to change anything?

**Comment by BhavyaaArora-08** [comment]
id, name, email, phoneNo, Address, createdAt
