### ISSUE TITLE
Get a particular user profile

### ISSUE THREAD

**Issue by BhavyaaArora-08** [sanscript-tech/medical-emergency-flutter-node#47]
@route GET api/profile/:id 
@desc Get a user profile 
@access Public

**Comment by Arnab-31** [comment]
Please assign this issue to me

**Comment by Arnab-31** [comment]
@Codess08 Should the output be id, name, email, phoneNo, Address, createdAt for this route too?

**Comment by BhavyaaArora-08** [comment]
yes.
