### ISSUE TITLE
Delete User/Deactivate account

### ISSUE THREAD

**Issue by BhavyaaArora-08** [sanscript-tech/medical-emergency-flutter-node#49]
@route DELETE api/profile/me 
@desc Delete profile, user 
@access Private

**Comment by Arnab-31** [comment]
I would like to work on this issue

**Comment by BhavyaaArora-08** [comment]
go ahead.

**Comment by BhavyaaArora-08** [comment]
Gentle reminder : No one will be awarded points after 20th November for a merged PR.
