### ISSUE TITLE
Update File Structure

### ISSUE THREAD

**Issue by BhavyaaArora-08** [sanscript-tech/medical-emergency-flutter-node#65]
![ss](https://user-images.githubusercontent.com/44175278/97748850-1fb23280-1b14-11eb-973f-7334c8d72813.jpg)

**Comment by Arnab-31** [comment]
Please assign this issue to me.

**Comment by Arnab-31** [comment]
@Codess08 can you merge the PR #59 so that I can update it's file structure?

**Comment by BhavyaaArora-08** [comment]
You could have updated file structure regardless,
but I have merged the PR.

**Comment by Arnab-31** [comment]
I have some doubts - 
1. What will be in the config folder?
2. The database will be connected in the mongoose folder. Am I right? 
3. Will the package.json and package-lock.json file be inside the src folder? If so then the node modules folder need to be inside as well
Thanks

**Comment by mbcse** [comment]
Hey @Arnab-31
 - The config folder contains all the configuration files like database connection, passport configuration, and keys.
- Put that in the database.js file in the config folder.
- We can keep it anywhere, I would recommend to put the package.json file outside of src to keep it cleaner, so in the start script, you need to just write "node src/server.js"
