### ISSUE TITLE
Basic Design 

### ISSUE THREAD

**Issue by suntwalriya** [sanscript-tech/medical-emergency-flutter-node#8]
- The starting app code

**Comment by Sapna2001** [comment]
Can I work on this?

**Comment by Sapna2001** [comment]
@carrisunrio what all should be included in the basic design?

**Comment by suntwalriya** [comment]
we have discussed it all in the meeting

**Comment by manthanguptaa** [comment]
@carrisunrio what's to be done in this issue?

**Comment by suntwalriya** [comment]
it was there before if anybody had to suggest any mockups before we built one, i think we can close this now.
