### ISSUE TITLE
Logo Designing

### ISSUE THREAD

**Issue by suntwalriya** [sanscript-tech/medical-emergency-flutter-node#9]
- Relevant designs would be considered acc to the color combo decided

**Comment by ishitakeshawani** [comment]
I would like to contribute to this issue. please assign me it.

**Comment by samflab** [comment]
Just a suggestion: We might need a logo for our application.

**Comment by suntwalriya** [comment]
@ishitakeshawani any Updates?

**Comment by Albert-Jokelin** [comment]
Can I work on this?

**Comment by ishitakeshawani** [comment]
The logo is ready. I'll push it tomorrow.you can find any other issue.
