### ISSUE TITLE
Doctor's list

### ISSUE THREAD

**Issue by suntwalriya** [sanscript-tech/medical-emergency-flutter-node#99]
The following should be made w.r.t the UI for a mobile device for the user-side with same colour combination as mentioned in the file structure.
![image](https://user-images.githubusercontent.com/41776149/98937348-460ca080-250c-11eb-8936-a4091e2ed043.png)
![image](https://user-images.githubusercontent.com/41776149/98937360-4d33ae80-250c-11eb-9e74-b89cf8b12580.png)

**Comment by samflab** [comment]
working on this issue
